import clsx from 'clsx'
import type { Metadata } from 'next'
import { Anton, Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const anton = Anton({ subsets: ['latin'], weight: '400', variable: '--font-anton' })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' className={clsx(`${inter.variable} ${anton.variable}`, 'scroll-smooth')}>
            <body className={clsx(inter.className, 'overflow-x-hidden')}>{children}</body>
        </html>
    )
}
